version: '3'
services:
  mongoapi:
    image: arpanet80/seguim-mongo
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seguim-mongo
    ports:
      - 3001:3000
    restart: always
    environment:
      MONGODB: 'mongodb+srv://arpanet80:Dante2011@clusterdespliegue.jmodcqi.mongodb.net/despliegueted'
      PORT: 3000
